package mx.tecno.dto;

// Generated 27/11/2011 09:30:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

	private Integer idproducto;
	private String nombre;
	private String modelo;
	private String marca;
	private int existencia;
	private String detalles;
	private float precioUnitario;
	private String categoria;
	private Set ventas = new HashSet(0);
	private Set proveedors = new HashSet(0);
	private Set compras = new HashSet(0);

	public Producto() {
	}

	public Producto(String nombre, String modelo, String marca, int existencia,
			String detalles, float precioUnitario, String categoria) {
		this.nombre = nombre;
		this.modelo = modelo;
		this.marca = marca;
		this.existencia = existencia;
		this.detalles = detalles;
		this.precioUnitario = precioUnitario;
		this.categoria = categoria;
	}

	public Producto(String nombre, String modelo, String marca, int existencia,
			String detalles, float precioUnitario, String categoria,
			Set ventas, Set proveedors, Set compras) {
		this.nombre = nombre;
		this.modelo = modelo;
		this.marca = marca;
		this.existencia = existencia;
		this.detalles = detalles;
		this.precioUnitario = precioUnitario;
		this.categoria = categoria;
		this.ventas = ventas;
		this.proveedors = proveedors;
		this.compras = compras;
	}

	public Integer getIdproducto() {
		return this.idproducto;
	}

	public void setIdproducto(Integer idproducto) {
		this.idproducto = idproducto;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	public int getExistencia() {
		return this.existencia;
	}

	public void setExistencia(int existencia) {
		this.existencia = existencia;
	}

	public String getDetalles() {
		return this.detalles;
	}

	public void setDetalles(String detalles) {
		this.detalles = detalles;
	}

	public float getPrecioUnitario() {
		return this.precioUnitario;
	}

	public void setPrecioUnitario(float precioUnitario) {
		this.precioUnitario = precioUnitario;
	}

	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	public Set getVentas() {
		return this.ventas;
	}

	public void setVentas(Set ventas) {
		this.ventas = ventas;
	}

	public Set getProveedors() {
		return this.proveedors;
	}

	public void setProveedors(Set proveedors) {
		this.proveedors = proveedors;
	}

	public Set getCompras() {
		return this.compras;
	}

	public void setCompras(Set compras) {
		this.compras = compras;
	}

}
