package mx.tecno.dto;

// Generated 27/11/2011 09:30:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Venta generated by hbm2java
 */
public class Venta implements java.io.Serializable {

	private Integer autoincremento;
	private Usuario usuario;
	private Producto producto;
	private Date fecha;
	private int cantidad;

	public Venta() {
	}

	public Venta(Usuario usuario, Producto producto, Date fecha, int cantidad) {
		this.usuario = usuario;
		this.producto = producto;
		this.fecha = fecha;
		this.cantidad = cantidad;
	}

	public Integer getAutoincremento() {
		return this.autoincremento;
	}

	public void setAutoincremento(Integer autoincremento) {
		this.autoincremento = autoincremento;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

}
